from temporalio import activity
import os
import tempfile
import subprocess
import shutil
import logging
from pydantic import BaseModel
from typing import Tuple, Dict, Any, Optional

class DevActionInput(BaseModel):
    bug_id: int
    title: str
    description: str
    category: str
    status: str

@activity.defn
async def setup_repository(input_data: DevActionInput) -> Tuple[str, str]:
    """Clones the repository and checks out a new branch."""
    github_token = os.getenv("GITHUB_ACCESS_TOKEN")
    if not github_token:
        raise ValueError("GITHUB_ACCESS_TOKEN not set in environment.")

    repo_url = os.getenv("GITHUB_REPO_URL", "https://github.com/singforhope/phwb.git")
    
    # We embed the token in the URL for cloning
    auth_repo_url = repo_url.replace("https://", f"https://oauth2:{github_token}@")

    workspace_dir = tempfile.mkdtemp(prefix=f"phwb_bug_{input_data.bug_id}_")
    branch_name = f"fix/bug-{input_data.bug_id}"

    logging.info(f"Cloning repo into {workspace_dir}")
    
    try:
        # Clone repo
        subprocess.run(
            ["git", "clone", auth_repo_url, "."],
            cwd=workspace_dir,
            check=True,
            capture_output=True,
            text=True
        )
        
        # Create and checkout new branch
        subprocess.run(
            ["git", "checkout", "-b", branch_name],
            cwd=workspace_dir,
            check=True,
            capture_output=True,
            text=True
        )
        return workspace_dir, branch_name
    except subprocess.CalledProcessError as e:
        logging.error(f"Git clone failed: {e.stderr}")
        raise

@activity.defn
async def analyze_and_code(config: Dict[str, Any]) -> None:
    """Invokes the LangChain LLM to analyze the bug and write code changes."""
    repo_path = config["repo_path"]
    bug_data = DevActionInput(**config["bug_data"])
    last_error = config.get("last_error")

    # TODO: This will use LangChain agent (created in agents/dev_agent.py) to explore the codebase
    # and write files. For now we will structure the call to the agent.
    
    from app.agents.dev_agent import run_dev_agent
    
    prompt = f"Fix Bug #{bug_data.bug_id}: {bug_data.title}\nDescription: {bug_data.description}\nCategory: {bug_data.category}"
    if last_error:
        prompt += f"\n\nThe previous attempt failed the verification step with this error:\n{last_error}\nPlease fix the issue."

    await run_dev_agent(repo_path, prompt)


@activity.defn
async def verify_fix(repo_path: str) -> Tuple[bool, Optional[str]]:
    """Runs tests and linters in the cloned repo to verify the fix."""
    logging.info(f"Verifying fix in {repo_path}")
    
    try:
        # 1. Install dependencies
        subprocess.run(
            ["npm", "install"],
            cwd=repo_path,
            check=True,
            capture_output=True,
            text=True
        )
        
        # 2. Run checks (svelte-check, lint, etc.)
        result = subprocess.run(
            ["npm", "run", "check"],
            cwd=repo_path,
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            return True, None
        else:
            return False, result.stderr or result.stdout
            
    except subprocess.CalledProcessError as e:
        return False, f"Setup Failed: {e.stderr}"
    except Exception as e:
        return False, f"Unexpected error: {str(e)}"


@activity.defn
async def create_pull_request(config: Dict[str, Any]) -> str:
    """Commits code, pushes branch, and uses PyGithub to raise PR."""
    repo_path = config["repo_path"]
    branch_name = config["branch_name"]
    bug_data = DevActionInput(**config["bug_data"])
    
    github_token = os.getenv("GITHUB_ACCESS_TOKEN")
    
    # 1. Commit and push
    try:
        subprocess.run(["git", "add", "."], cwd=repo_path, check=True)
        subprocess.run(
            ["git", "commit", "-m", f"Fixes #{bug_data.bug_id}: {bug_data.title}"],
            cwd=repo_path, check=True
        )
        subprocess.run(
            ["git", "push", "origin", branch_name],
            cwd=repo_path, check=True
        )
    except subprocess.CalledProcessError as e:
        logging.error(f"Failed to commit/push: {e}")
        raise

    # 2. Raise PR using PyGithub
    from github import Github
    g = Github(github_token)
    
    # Needs the repo format exactly as "org/repo"
    repo_url = os.getenv("GITHUB_REPO_URL", "https://github.com/singforhope/phwb.git")
    repo_name = repo_url.split("github.com/")[-1].replace(".git", "")
    
    repo = g.get_repo(repo_name)
    
    pr = repo.create_pull(
        title=f"Fix: {bug_data.title} (Bug #{bug_data.bug_id})",
        body=f"Automated PR generated by DevAgent to fix bug #{bug_data.bug_id}.\n\n{bug_data.description}",
        head=branch_name,
        base="main"
    )
    
    return pr.html_url


@activity.defn
async def update_bug_ticket(config: Dict[str, Any]) -> None:
    """Updates Supabase bug ticket with the PR link."""
    from app.supabase_client import get_supabase_client
    supabase = get_supabase_client()
    
    bug_id = config["bug_id"]
    pr_url = config.get("pr_url")
    error_msg = config.get("error_msg")
    
    if pr_url:
        # Add comment
        supabase.table("phwb_bug_comments").insert({
            "bug_id": bug_id,
            "comment": f"✅ The Development Agent has completed a fix and raised a Pull Request.\n\nPlease review it here: {pr_url}",
        }).execute()
        
        # Update status
        supabase.table("phwb_bugs").update({
            "status": "review"
        }).eq("id", bug_id).execute()
        
    elif error_msg:
        supabase.table("phwb_bug_comments").insert({
            "bug_id": bug_id,
            "comment": f"❌ The Development Agent encountered an unrecoverable error during execution:\n\n```\n{error_msg}\n```",
        }).execute()
